config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  get 'static_pages/contact'
  devise_for :users
  root 'events#index'

  resources :users, :only => [:show]
  resources :events
  resources :attendances
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :event
    belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, class_name: "User", foreign_key: "user_id", dependent: :destroy
    has_many :attendances, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :attendances, dependent: :destroy
    has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
      @events = Event.all
  end

  def show
      @event = Event.find(params[:id])
  end

  def edit
      @event = Event.find(params[:id])
  end

  def update
      @event = Event.find(params[:id])
      event_params = params.require(:event).permit(:title, :content)
      @event.update(event_params)
      redirect_to events_path
  end
  
  def new
      @event = Event.new
  end

  def create
      event = Event.create(event_params)
      redirect_to events_path
  end
  
  def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to events_path
  end

  #######
  private
  #######

  def event_params
      params.require(:event).permit(:title, :content)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]

  
  def index
    
  end

  def secret
    
  end

  def contact
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<html lang="en">
    <header class="text-center">
        <h1>Modifier un événement</h1>
    </header>

    <body>
        <%= form_with model: @event do |f| %>
            <div class="form-group">
                <label>Titre de l'événement :</label>
                <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
                <label>Description de l'événement :</label>
                <%= f.text_area :description, class: "form-control" %>
            </div>

            <p><%= @event.admin.first_name %></p>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Modifier</button>
            </div>
        <% end %>
    </body>
</html>

app/views/events/index.html.erb
<html lang="en">
    <header class="text-center">
        <h4><FONT color="#263238"><B>Retrouve tous nos évéments, fais de nouvelles rencontres et crées des souvenirs inoubliables !</B></FONT></h4>
    </header>
    <p></p>
    <body>
    <% @events.each do |event| %>
        <p><B><FONT color="#455A64">&#10145;&#65039 Événement : "<%= event.title %>"</FONT></B></p>
        <p><FONT color="#455A64">Description : <%= event.description %></FONT></p>
        <p><FONT color="#455A64">Créé par <%= event.admin.first_name %></FONT></p>
        <p>
        <a href="<%= event_path(event.id) %>" class="btn btn-primary">En savoir plus</a>
        </p>
    </body>
<% end %>

app/views/events/new.html.erb
<html lang="en">
    <header class="text-center">
        <h2><FONT color="#263238">Tu veux créer un nouvel évément ? &#128526</FONT></h2>
    </header>
<p></p>
    <body>
        <%= form_with model: @event do |f| %>
            <div class="form-group">
                <label>Nom de l'événement</label>
                <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
                <label>Description de l'évenement</label>
                <%= f.text_area :description, class: "form-control" %>
            </div>

            <div class="form-group" style="padding-top: 1rem;">  
                <button type="submit" class="btn btn-primary">Ajouter</button>
            </div>
        <% end %>
    </body>
</html>

app/views/events/show.html.erb
<html lang="en">
    <header class="text-center">
        <h2><FONT color="#263238">Nom de l'événement : <%= @event.title %></h2>
    </header>
    <body>
        <p>Ce qu'il faut savoir : <%= @event.description %></p>
        <p>Créé par <%= @event.admin.first_name %></p>
        <p><a href="/" class="btn btn-primary">Revenir en arrière</a></p>
    </body>
</html>

app/views/layouts/_navbar.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="<%= root_path %>" class="nav-link px-2 link-secondary-strong">	&#127968; Accueil</a></li>
      <li><a href="<%= events_path %>" class="nav-link px-2 link-dark">	&#127870; Événement du jour</a></li>
      <% if user_signed_in? %>
      <li><a href="<%= new_event_path %>" class="nav-link px-2 link-dark">&#127942; Créer un évément</a></li>
      <%end%>
      <% if user_signed_in? %>
      <li><a href="<%=user_path(current_user.id)%>" class="nav-link px-2 link-dark">&#128124; Ton profil</a></li>
      <%end%>
      <li><a href="<%= static_pages_contact_path %>" class="nav-link px-2 link-dark">&#127384; Contact</a></li>
    </ul>

    <div class="dropdown">
    <% if user_signed_in? %>
      <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Welcome bitch</button>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        <li><a class="dropdown-item" href="<%=user_path(current_user.id)%>">Ton profil</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="<%=destroy_user_session_path%>" data-method='delete'>Se déconnecter</a></li>
      </ul>
    <% else %>
      <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Come here baby</button>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        <li><a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a></li> 
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a></li> 
      </ul>
      <%end%>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </head>

  <body>
  <%= render "layouts/navbar" %>
  <div class="container" style="padding-top: 1rem;">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="container contact-form">
  <form method="post">
  <h3>Un petit mot doux ? Une question ? Un pb ? &#128221; &#128525; Call us mon choux!</h3></br>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
      </div>
      <p></p>
      <div class="form-group">
        <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
      </div>
      <p></p>
      <div class="form-group">
        <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
      </div>
      <p></p>
        <div class="form-group">
          <input type="submit" name="btnSubmit" class="btnContact" value="Envoyez un mess" />
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
        </div>
      </div>
    </div>
  </form>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<html lang="en">
    <header class="text-center">
        <h2><FONT color="#263238">Salut <%= @user.first_name %>, bienvenue parmi nous ! </FONT></h2>
    </header>
    <p></p>
    <body>
        <h5> Voici les infos te concernant &#10549;&#65039;</h5>
        <p></p>
        <p>	&#10024; Ton nom et prénom : <%= @user.first_name %><%= @user.last_name %></p>
        <p>	&#10024; L'email associé à ton compte : <%= @user.email %></p>
        <p>	&#10024; Ta description : <%= @user.description %></p>
        <p>	&#10024; Les événements auxquels tu participes : <%= @user.description %></p>
        <p>	&#10024; Les événements que tu as créé : <%= @user.description %></p>
        <p><a href="/" class="btn btn-primary">Retour</a></p>
    </body>
</html>